using FirstWebApplication.Models;
using FirstWebApplication.Models.ViewModel;
using FirstWebApplication.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

    namespace FirstWebApplication.Controllers
{
    /// <summary>
    /// Controller for notification functionality. Handles display of comments/reports on user's obstacles.
    /// </summary>
    [Authorize]
    public class VarslingController : Controller
    {
        private readonly IRegistrarRepository _registrarRepository;
        private readonly IObstacleRepository _obstacleRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public VarslingController(
            IRegistrarRepository registrarRepository,
            IObstacleRepository obstacleRepository,
            UserManager<ApplicationUser> userManager)
        {
            _registrarRepository = registrarRepository;
            _obstacleRepository = obstacleRepository;
            _userManager = userManager;
        }

        /// <summary>
        /// Displays all notifications (comments/reports) for obstacles owned by the logged-in user. Filters out auto-generated comments and groups by obstacle.
        /// </summary>
        /// <returns>The notifications view with grouped comments by obstacle</returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // Get logged-in user
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return View(new List<VarslingViewModel>());
            }

            // Get all reports
            var allRapports = await _registrarRepository.GetAllRapports();
            
            // Filter out auto-generated comments
            var comments = FilterOutAutoGeneratedComments(allRapports).ToList();
            
            // Get obstacles that belong to the logged-in user
            var userObstacles = await _obstacleRepository.GetObstaclesByOwner(currentUser.Id);
            var userObstacleIds = userObstacles.Select(o => o.ObstacleId).ToHashSet();
            
            // Filter comments to only obstacles that belong to the user
            var userComments = comments
                .Where(r => r.Obstacle != null && userObstacleIds.Contains(r.Obstacle.ObstacleId))
                .ToList();
            
            // Save the highest RapportID the user has seen (marks all notifications with lower or equal ID as seen)
            var maxRapportId = userComments.Any() ? userComments.Max(r => r.RapportID) : 0;
            HttpContext.Session.SetInt32($"LastViewedRapportId_{currentUser.Id}", maxRapportId);
            
            // Group comments by ObstacleId
            var groupedComments = userComments
                .Where(r => r.Obstacle != null)
                .GroupBy(r => r.ObstacleId)
                .ToList();
            
            // Create ViewModel for each obstacle with comments
            var varslinger = new List<VarslingViewModel>();
            
            foreach (var group in groupedComments)
            {
                var obstacleId = group.Key;
                var obstacle = await _obstacleRepository.GetElementById(obstacleId);
                
                if (obstacle != null)
                {
                    var obstacleComments = group.OrderByDescending(r => r.RapportID).ToList();
                    
                    varslinger.Add(new VarslingViewModel
                    {
                        Obstacle = obstacle,
                        CommentCount = obstacleComments.Count,
                        Comments = obstacleComments
                    });
                }
            }
            
            // Sort by newest comment first
            varslinger = varslinger
                .OrderByDescending(v => v.Comments.FirstOrDefault()?.RapportID ?? 0)
                .ToList();
            
            return View(varslinger);
        }

        /// <summary>
        /// Displays detailed view of an obstacle and its reports for the logged-in user
        /// </summary>
        /// <param name="obstacleId">The ID of the obstacle to view</param>
        /// <returns>The obstacle details view, or redirects to index if obstacle not found</returns>
        [HttpGet]
        public async Task<IActionResult> Details(int obstacleId)
        {
            // Placeholder - this will be shown later
            // Should display overview of report similar to DetaljerOmRapport.cshtml but with editing access
            var obstacle = await _obstacleRepository.GetElementById(obstacleId);
            if (obstacle == null)
            {
                TempData["Error"] = "Fant ikke hindring.";
                return RedirectToAction(nameof(Index));
            }
            
            var rapports = await _registrarRepository.GetAllRapports();
            var obstacleRapports = rapports.Where(r => r.ObstacleId == obstacleId).ToList();
            
            ViewBag.Obstacle = obstacle;
            ViewBag.Rapports = obstacleRapports;
            
            return View(obstacle);
        }

        /// <summary>
        /// Gets the count of new/unread notifications (comments from admin/registerfører) for the current user
        /// </summary>
        /// <returns>JSON object with the notification count</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetNotificationCount()
        {
            if (!User.Identity?.IsAuthenticated ?? true)
            {
                return Json(new { count = 0 });
            }

            try
            {
                var currentUser = await _userManager.GetUserAsync(User);
                if (currentUser == null)
                {
                    return Json(new { count = 0 });
                }

                // Get the highest RapportID the user has seen
                var lastViewedRapportId = HttpContext.Session.GetInt32($"LastViewedRapportId_{currentUser.Id}") ?? 0;

                // Get all reports
                var allRapports = await _registrarRepository.GetAllRapports();
                
                // Filter out auto-generated comments
                var comments = FilterOutAutoGeneratedComments(allRapports).ToList();

                // Filter only notifications for obstacles that belong to the logged-in user
                var userObstacles = await _obstacleRepository.GetObstaclesByOwner(currentUser.Id);
                var userObstacleIds = userObstacles.Select(o => o.ObstacleId).ToHashSet();

                // Filter out notifications that the user has already seen (RapportID <= lastViewedRapportId)
                var unreadNotifications = comments
                    .Where(r => r.Obstacle != null && 
                               userObstacleIds.Contains(r.Obstacle.ObstacleId) &&
                               r.RapportID > lastViewedRapportId)
                    .ToList();

                var count = unreadNotifications.Count;

                return Json(new { count = count });
            }
            catch
            {
                return Json(new { count = 0 });
            }
        }

        /// <summary>
        /// Helper method to filter out auto-generated comments
        /// </summary>
        /// <param name="rapports">The list of reports to filter</param>
        /// <returns>Filtered list of reports without auto-generated comments</returns>
        private IEnumerable<RapportData> FilterOutAutoGeneratedComments(IEnumerable<RapportData> rapports)
        {
            return rapports.Where(r => !(r.RapportComment.StartsWith("Hindring '") && 
                                        r.RapportComment.Contains(" ble sendt inn. Høyde:")));
        }
    }
}

