using FirstWebApplication.Models;

namespace FirstWebApplication.Repositories
{
    /// <summary>
    /// Repository interface for report/rapport data operations
    /// </summary>
    public interface IRegistrarRepository
    {
        /// <summary>
        /// Adds a new report
        /// </summary>
        Task<RapportData> AddRapport(RapportData rapport);
        
        /// <summary>
        /// Gets all reports
        /// </summary>
        Task<IEnumerable<RapportData>> GetAllRapports();
        
        /// <summary>
        /// Updates an existing report
        /// </summary>
        Task<RapportData> UpdateRapport(RapportData rapports);
        
        /// <summary>
        /// Gets all reports associated with a specific obstacle
        /// </summary>
        /// <param name="obstacleId">The ID of the obstacle</param>
        /// <returns>List of reports for the obstacle</returns>
        Task<List<RapportData>> GetRapportsByObstacleId(int obstacleId);
        
        /// <summary>
        /// Gets all reports excluding auto-generated comments (those starting with "Hindring '" and containing " ble sendt inn. Høyde:")
        /// </summary>
        /// <returns>List of reports without auto-generated comments</returns>
        Task<List<RapportData>> GetRapportsExcludingAutoGenerated();
        
        /// <summary>
        /// Gets all reports for obstacles owned by a specific user, excluding auto-generated comments
        /// </summary>
        /// <param name="userObstacleIds">The set of obstacle IDs owned by the user</param>
        /// <returns>List of reports for user's obstacles</returns>
        Task<List<RapportData>> GetRapportsForUserObstacles(HashSet<int> userObstacleIds);
        
        /// <summary>
        /// Adds a report/comment to an obstacle
        /// </summary>
        /// <param name="obstacleId">The ID of the obstacle</param>
        /// <param name="comment">The comment text to add</param>
        /// <returns>The created report</returns>
        Task<RapportData> AddRapportToObstacle(int obstacleId, string comment);
        
        /// <summary>
        /// Gets the count of unread notifications (reports with RapportID > lastViewedRapportId) for a user's obstacles
        /// </summary>
        /// <param name="userObstacleIds">The set of obstacle IDs owned by the user</param>
        /// <param name="lastViewedRapportId">The highest RapportID the user has seen</param>
        /// <returns>Count of unread notifications</returns>
        Task<int> GetUnreadNotificationsCount(HashSet<int> userObstacleIds, int lastViewedRapportId);
        
        /// <summary>
        /// Generates report message for quick save operation
        /// </summary>
        /// <param name="obstacle">The saved obstacle</param>
        /// <returns>Formatted report message for quick save</returns>
        string GenerateQuickSaveReportMessage(ObstacleData obstacle);
        
        /// <summary>
        /// Generates report message for full submit operation
        /// </summary>
        /// <param name="obstacle">The saved obstacle</param>
        /// <returns>Formatted report message for full submit</returns>
        string GenerateSubmitReportMessage(ObstacleData obstacle);
        
        /// <summary>
        /// Generates report message for obstacle update operation
        /// </summary>
        /// <param name="obstacle">The updated obstacle</param>
        /// <param name="newHeight">The new height value</param>
        /// <returns>Formatted report message for obstacle update</returns>
        string GenerateUpdateReportMessage(ObstacleData obstacle, double newHeight);
    }
}
