using FirstWebApplication.Models;

namespace FirstWebApplication.Repositories
{
    // Repository-grensesnitt for rapport/rapport dataoperasjoner
    public interface IRegistrarRepository
    {
        // Legger til en ny rapport
        Task<RapportData> AddRapport(RapportData rapport);
        
        // Henter alle rapporter
        Task<IEnumerable<RapportData>> GetAllRapports();
        
        // Oppdaterer en eksisterende rapport
        Task<RapportData> UpdateRapport(RapportData rapports);
        
        // Henter alle rapporter tilknyttet en spesifikk hindring
        Task<List<RapportData>> GetRapportsByObstacleId(int obstacleId);
        
        // Henter alle rapporter ekskludert auto-genererte kommentarer (de som starter med "Hindring '" og inneholder " ble sendt inn. Høyde:")
        Task<List<RapportData>> GetRapportsExcludingAutoGenerated();
        
        // Henter alle rapporter for hindringer eid av en spesifikk bruker, ekskludert auto-genererte kommentarer
        Task<List<RapportData>> GetRapportsForUserObstacles(HashSet<int> userObstacleIds);
        
        // Legger til en rapport/kommentar til en hindring
        Task<RapportData> AddRapportToObstacle(int obstacleId, string comment);
        
        // Henter antall uleste varslinger (rapporter med RapportID > lastViewedRapportId) for en brukers hindringer
        Task<int> GetUnreadNotificationsCount(HashSet<int> userObstacleIds, int lastViewedRapportId);
        
        // Genererer rapportmelding for hurtiglagringsoperasjon
        string GenerateQuickSaveReportMessage(ObstacleData obstacle);
        
        // Genererer rapportmelding for full innsendingsoperasjon
        string GenerateSubmitReportMessage(ObstacleData obstacle);
        
        // Genererer rapportmelding for hindringsoppdateringsoperasjon
        string GenerateUpdateReportMessage(ObstacleData obstacle, double newHeight);
    }
}
