using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstWebApplication.DataContext;
using FirstWebApplication.Models;
using Microsoft.EntityFrameworkCore;

namespace FirstWebApplication.Repositories
{
    // Repository for rapport/rapport dataoperasjoner
    public class RegistrarRepository : IRegistrarRepository
    {
        private readonly ApplicationDBContext _context;

        public RegistrarRepository(ApplicationDBContext context)
        {
            _context = context;
        }

        // Legger til en ny rapport
        public async Task<RapportData> AddRapport(RapportData rapport)
        {
            await _context.Rapports.AddAsync(rapport);
            await _context.SaveChangesAsync();
            return rapport;
        }

        // Henter de 50 nyeste rapportene med deres tilknyttede hindringer
        public async Task<IEnumerable<RapportData>> GetAllRapports()
        {
            return await _context.Rapports
                .Include(r => r.Obstacle)
                    .ThenInclude(o => o.OwnerUser)
                .OrderByDescending(r => r.RapportID)
                .Take(50)
                .ToListAsync();
        }

        // Oppdaterer en eksisterende rapport
        public async Task<RapportData> UpdateRapport(RapportData rapport)
        {
            _context.Rapports.Update(rapport);
            await _context.SaveChangesAsync();
            return rapport;
        }

        // Henter alle rapporter tilknyttet en spesifikk hindring
        public async Task<List<RapportData>> GetRapportsByObstacleId(int obstacleId)
        {
            return await _context.Rapports
                .Include(r => r.Obstacle)
                    .ThenInclude(o => o.OwnerUser)
                .Where(r => r.ObstacleId == obstacleId)
                .OrderByDescending(r => r.RapportID)
                .ToListAsync();
        }

        // Henter alle rapporter ekskludert auto-genererte kommentarer (de som starter med "Hindring '" og inneholder " ble sendt inn. Høyde:")
        public async Task<List<RapportData>> GetRapportsExcludingAutoGenerated()
        {
            var allRapports = await GetAllRapports();
            return allRapports
                .Where(r => !(r.RapportComment.StartsWith("Hindring '") &&
                              r.RapportComment.Contains(" ble sendt inn. Høyde:")))
                .ToList();
        }

        // Henter alle rapporter for hindringer eid av en spesifikk bruker, ekskludert auto-genererte kommentarer
        public async Task<List<RapportData>> GetRapportsForUserObstacles(HashSet<int> userObstacleIds)
        {
            var filteredRapports = await GetRapportsExcludingAutoGenerated();
            return filteredRapports
                .Where(r => r.Obstacle != null && userObstacleIds.Contains(r.Obstacle.ObstacleId))
                .ToList();
        }

        // Legger til en rapport/kommentar til en hindring
        public async Task<RapportData> AddRapportToObstacle(int obstacleId, string comment)
        {
            var rapport = new RapportData
            {
                ObstacleId = obstacleId,
                RapportComment = comment
            };

            return await AddRapport(rapport);
        }

        // Henter antall uleste varslinger (rapporter med RapportID > lastViewedRapportId) for en brukers hindringer
        public async Task<int> GetUnreadNotificationsCount(HashSet<int> userObstacleIds, int lastViewedRapportId)
        {
            var userComments = await GetRapportsForUserObstacles(userObstacleIds);
            return userComments
                .Where(r => r.RapportID > lastViewedRapportId)
                .Count();
        }

        // Genererer rapportmelding for hurtiglagringsoperasjon
        public string GenerateQuickSaveReportMessage(ObstacleData obstacle)
        {
            string obstacleName;
            if (string.IsNullOrEmpty(obstacle.ObstacleName))
                obstacleName = "Ikke navngitt";
            else
                obstacleName = obstacle.ObstacleName;

            string heightInfo;
            if (obstacle.ObstacleHeight > 0)
                heightInfo = $"Høyde: {obstacle.ObstacleHeight}m. ";
            else
                heightInfo = "";

            string descriptionInfo;
            if (!string.IsNullOrEmpty(obstacle.ObstacleDescription))
                descriptionInfo = obstacle.ObstacleDescription;
            else
                descriptionInfo = "";

            return $"Hindring '{obstacleName}' ble hurtiglagret. {heightInfo}{descriptionInfo}";
        }

        // Genererer rapportmelding for full innsendingsoperasjon
        public string GenerateSubmitReportMessage(ObstacleData obstacle)
        {
            return $"Hindring '{obstacle.ObstacleName}' ble sendt inn. Høyde: {obstacle.ObstacleHeight}m. {obstacle.ObstacleDescription}";
        }

        // Genererer rapportmelding for hindringsoppdateringsoperasjon
        public string GenerateUpdateReportMessage(ObstacleData obstacle, double newHeight)
        {
            return $"Piloten oppdaterte hindringen. Ny høyde: {newHeight}m.";
        }
    }
}
