using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstWebApplication.DataContext;
using FirstWebApplication.Models;
using Microsoft.EntityFrameworkCore;

namespace FirstWebApplication.Repositories
{
    /// <summary>
    /// Repository for report/rapport data operations
    /// </summary>
    public class RegistrarRepository : IRegistrarRepository
    {
        private readonly ApplicationDBContext _context;

        public RegistrarRepository(ApplicationDBContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Adds a new report
        /// </summary>
        public async Task<RapportData> AddRapport(RapportData rapport)
        {
            await _context.Rapports.AddAsync(rapport);
            await _context.SaveChangesAsync();
            return rapport;
        }

        /// <summary>
        /// Gets the 50 most recent reports with their associated obstacles
        /// </summary>
        public async Task<IEnumerable<RapportData>> GetAllRapports()
        {
            return await _context.Rapports
                .Include(r => r.Obstacle)
                    .ThenInclude(o => o.OwnerUser)
                .OrderByDescending(r => r.RapportID)
                .Take(50)
                .ToListAsync();
        }

        /// <summary>
        /// Updates an existing report
        /// </summary>
        public async Task<RapportData> UpdateRapport(RapportData rapport)
        {
            _context.Rapports.Update(rapport);
            await _context.SaveChangesAsync();
            return rapport;
        }

        /// <summary>
        /// Gets all reports associated with a specific obstacle
        /// </summary>
        /// <param name="obstacleId">The ID of the obstacle</param>
        /// <returns>List of reports for the obstacle</returns>
        public async Task<List<RapportData>> GetRapportsByObstacleId(int obstacleId)
        {
            return await _context.Rapports
                .Include(r => r.Obstacle)
                    .ThenInclude(o => o.OwnerUser)
                .Where(r => r.ObstacleId == obstacleId)
                .OrderByDescending(r => r.RapportID)
                .ToListAsync();
        }

        /// <summary>
        /// Gets all reports excluding auto-generated comments (those starting with "Hindring '" and containing " ble sendt inn. Høyde:")
        /// </summary>
        /// <returns>List of reports without auto-generated comments</returns>
        public async Task<List<RapportData>> GetRapportsExcludingAutoGenerated()
        {
            var allRapports = await GetAllRapports();
            return allRapports
                .Where(r => !(r.RapportComment.StartsWith("Hindring '") &&
                              r.RapportComment.Contains(" ble sendt inn. Høyde:")))
                .ToList();
        }

        /// <summary>
        /// Gets all reports for obstacles owned by a specific user, excluding auto-generated comments
        /// </summary>
        /// <param name="userObstacleIds">The set of obstacle IDs owned by the user</param>
        /// <returns>List of reports for user's obstacles</returns>
        public async Task<List<RapportData>> GetRapportsForUserObstacles(HashSet<int> userObstacleIds)
        {
            var filteredRapports = await GetRapportsExcludingAutoGenerated();
            return filteredRapports
                .Where(r => r.Obstacle != null && userObstacleIds.Contains(r.Obstacle.ObstacleId))
                .ToList();
        }

        /// <summary>
        /// Adds a report/comment to an obstacle
        /// </summary>
        /// <param name="obstacleId">The ID of the obstacle</param>
        /// <param name="comment">The comment text to add</param>
        /// <returns>The created report</returns>
        public async Task<RapportData> AddRapportToObstacle(int obstacleId, string comment)
        {
            var rapport = new RapportData
            {
                ObstacleId = obstacleId,
                RapportComment = comment
            };

            return await AddRapport(rapport);
        }

        /// <summary>
        /// Gets the count of unread notifications (reports with RapportID > lastViewedRapportId) for a user's obstacles
        /// </summary>
        /// <param name="userObstacleIds">The set of obstacle IDs owned by the user</param>
        /// <param name="lastViewedRapportId">The highest RapportID the user has seen</param>
        /// <returns>Count of unread notifications</returns>
        public async Task<int> GetUnreadNotificationsCount(HashSet<int> userObstacleIds, int lastViewedRapportId)
        {
            var userComments = await GetRapportsForUserObstacles(userObstacleIds);
            return userComments
                .Where(r => r.RapportID > lastViewedRapportId)
                .Count();
        }

        /// <summary>
        /// Generates report message for quick save operation
        /// </summary>
        /// <param name="obstacle">The saved obstacle</param>
        /// <returns>Formatted report message for quick save</returns>
        public string GenerateQuickSaveReportMessage(ObstacleData obstacle)
        {
            string obstacleName;
            if (string.IsNullOrEmpty(obstacle.ObstacleName))
                obstacleName = "Ikke navngitt";
            else
                obstacleName = obstacle.ObstacleName;

            string heightInfo;
            if (obstacle.ObstacleHeight > 0)
                heightInfo = $"Høyde: {obstacle.ObstacleHeight}m. ";
            else
                heightInfo = "";

            string descriptionInfo;
            if (!string.IsNullOrEmpty(obstacle.ObstacleDescription))
                descriptionInfo = obstacle.ObstacleDescription;
            else
                descriptionInfo = "";

            return $"Hindring '{obstacleName}' ble hurtiglagret. {heightInfo}{descriptionInfo}";
        }

        /// <summary>
        /// Generates report message for full submit operation
        /// </summary>
        /// <param name="obstacle">The saved obstacle</param>
        /// <returns>Formatted report message for full submit</returns>
        public string GenerateSubmitReportMessage(ObstacleData obstacle)
        {
            return $"Hindring '{obstacle.ObstacleName}' ble sendt inn. Høyde: {obstacle.ObstacleHeight}m. {obstacle.ObstacleDescription}";
        }

        /// <summary>
        /// Generates report message for obstacle update operation
        /// </summary>
        /// <param name="obstacle">The updated obstacle</param>
        /// <param name="newHeight">The new height value</param>
        /// <returns>Formatted report message for obstacle update</returns>
        public string GenerateUpdateReportMessage(ObstacleData obstacle, double newHeight)
        {
            return $"Piloten oppdaterte hindringen. Ny høyde: {newHeight}m.";
        }
    }
}
