name: .NET

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"] #forandre denne til main om du kun vil at den skal kjøres ved pull request til main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Setup cache for .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Restore dependencies
        run: dotnet restore FirstWebApplication.sln

      - name: Build
        run: dotnet build  FirstWebApplication.sln --no-restore

      - name: Test
        run: dotnet test  FirstWebApplication.sln --no-build --verbosity normal
